extends: substitution
message: Consider using '%s' instead of '%s'
level: warning
ignorecase: false
swap:
  agnostic: platform independent
  aka: also know as
  authN: authentication
  authZ: authroization
  below: later
  black friday: peak scale event
  blacklist: denylist
  blast radius: affected area
  blue/green: blue-green
  bonkers: baffling
  break-glass: emergency access
  cellphone: mobile device
  cellular: mobile
  check box: checkbox
  cons: disadvantage
  content type: media type
  could: can
  crazy: complex
  cripple: slow down
  curated role: predefined roles
  demilitarized zone: perimeter network
  dmz: perimeter network
  denigrate: disparage
  desire: want
  disable: inactive
  does not yet: does not
  dojo: training
  downscope: reduce scope
  dumb: simplify
  dummy: placeholder
  e.g: for example
  female adapter: socket
  finale solution: last solution
  first-class: core feature
  first class: core feature
  for instance: for example
  grandfathered: exception
  grayed out: unavailable
  greyed out: unavailable
  graylist: provisional list
  greylist: provisional list
  guru: expert
  hands off: automated
  hands on: customizable
  hang: not responding
  hung: not responding
  healthy: responsvie
  unhealthy: unresponsive
  hit: press
  housekeeping: maintenance
  hover: hold the pointer over
  i.e.: that is
  impact: affect
  ingest: import
  insane: unexpected
  k8s: Kubernetes
  lame: deficient
  leverage: use
  lunatic: strange
  male adapter: plug
  master: primary
  mad: complex
  newer: later
  ninja: expert
  nonce: only once
  noops: fully managed
  nuke: remove
  off the shelf: prebiult
  old: earlier
  omnibox: address bar
  pets vs. cattle: persistent vs. dynamic
  postmortem: retrospective
  pros: advantage
  slave: secondary
  regex: regular expression
  repo: repository
  sanity check: confidence check
  sexy: elegant
  sherpa: guide
  spin up: start
  tarball: tar file
  terminate: exit
  traditional: conventional
  turn on: enable
  unarchive: extract
  uncheck: clear
  unselect: clear
  untar: extract
  unzip: extract
  vs: versus
  whitehat: ethical
  whitelist: allowlist
  wish: want
